# - name: check if template is already imported
#   shell: curl -XGET {{ lookup('template','roles/common/templates/rhev_curl_xml_params.j2') | trim }} \
#          "https://{{ hostvars['rhevm'].vm_nics[1].ip }}/api/templates" | \
#          xmllint --xpath "//template[starts-with(name,'RedHat_CFME')]" - || true
#   delegate_to: "{{ infrastructure_delegate_rhel7_host_used_to_perform_xpath_select_on_curl_results }}"
#   changed_when: false
#   register: template

- name: check if template is already imported
  shell: rhevm-shell -E 'list templates --query name=RedHat_CFME*' | awk '/^name/'
  delegate_to: rhevm
  changed_when: false
  register: template

- block:
    - name: get export domain UUID
      shell: curl -XGET {{ lookup('template','roles/common/templates/rhev_curl_xml_params.j2') | trim }} \
             "https://{{ hostvars['rhevm'].vm_nics[1].ip }}/api/storagedomains" | \
             xmllint --xpath "/storage_domains/storage_domain[name='export1']/@id" - | \
             awk 'match($0, /.*id="(.*)"/, m) { print m[1]  }'
      delegate_to: "{{ infrastructure_delegate_rhel7_host_used_to_perform_xpath_select_on_curl_results }}"
      register: export_domain_uuid
      failed_when: export_domain_uuid.stdout == ''
      changed_when: false

    - name: unpack the virtual appliance directly into the RHEV export domain (from layer1 binary dir)
      unarchive: copy=no src={{ layer1_binary_dir }}/{{ current_lifecycle_env.cloudforms_ova_appliance }} dest="{{ nfs_rhev_export_domain_path }}/{{ export_domain_uuid.stdout }}" owner=36 group=36
      delegate_to: "{{ infrastructure_delegate_nfs_server }}"
      when: (layer1_binary_dir is defined)
    - name: unpack the virtual appliance directly into the RHEV export domain (from ansible playbook host)
      unarchive: copy=no src=binary/{{ current_lifecycle_env.cloudforms_ova_appliance }} dest="{{ nfs_rhev_export_domain_path }}/{{ export_domain_uuid.stdout }}" owner=36 group=36
      delegate_to: "{{ infrastructure_delegate_nfs_server }}"
      when: (layer1_binary_dir is not defined)

    - name: get template import link
      shell: curl -XGET {{ lookup('template','roles/common/templates/rhev_curl_xml_params.j2') | trim }} \
             "https://{{ hostvars['rhevm'].vm_nics[1].ip }}/api/storagedomains/{{ export_domain_uuid.stdout }}/templates" | \
             xmllint --xpath "//template[starts-with(name,'RedHat_CFME')]/actions/link[@rel='import']/@href" - | \
             awk 'match($0, /.*href="(.*)"/, m) { print m[1]  }'
      delegate_to: "{{ infrastructure_delegate_rhel7_host_used_to_perform_xpath_select_on_curl_results }}"
      register: template_import_link
      failed_when: template_import_link.stdout == ''
      changed_when: false

    - name: import template
      shell: curl -XPOST {{ lookup('template','roles/common/templates/rhev_curl_xml_params.j2') | trim }} \
             -d "{{ lookup('template', 'import_template.xml.j2') }}" \
             "https://{{ hostvars['rhevm'].vm_nics[1].ip }}{{ template_import_link.stdout }}"
      delegate_to: "{{ infrastructure_delegate_rhel7_host_used_to_perform_xpath_select_on_curl_results }}"

    - name: pause for rhevm to react
      pause: seconds=15

    - name: get template name
      shell: rhevm-shell -E "list templates --parent-storagedomain-name export1" | awk '/^name.*RedHat_CFME/ { print $3 }'
      register: template_name
      delegate_to: rhevm
      changed_when: false
      failed_when: template_name.stdout == ""

    - name: remove template from export domain
      shell: rhevm-shell -E 'delete template {{ template_name.stdout }} --parent-storagedomain-name export1'
      delegate_to: rhevm
  when: template.stdout == ''
