- block:
    - include: import_cfme_template.yml
    - include: instantiate_cfme_template.yml

    # - name: start Cloudforms VM
    #   ovirt:
    #     user: admin@internal
    #     url: "https://{{ hostvars['rhevm'].ansible_host }}"
    #     instance_name: Cloudforms
    #     password: "{{ root_password }}"
    #     state: started
    #   delegate_to: rhevm

  when: mode == 'create'

- block:
    - name: find Cloudforms VM
      shell: rhevm-shell -E 'list vms --query "name=Cloudforms"' | awk /id/
      register: cloudforms_vm_id
      changed_when: false
      delegate_to: rhevm

    - name: stop Cloudforms VM
      ovirt:
        user: admin@internal
        url: "https://localhost"
        instance_name: Cloudforms
        password: "{{ root_password }}"
        state: shutdown
      delegate_to: rhevm
      when: cloudforms_vm_id.stdout != ""

    - name: wait for VM to shut down
      shell: curl -XGET {{ lookup('template','roles/common/templates/rhev_curl_xml_params.j2') | trim }} \
             "https://{{ hostvars['rhevm'].vm_nics[1].ip }}/api/vms" | \
             xmllint --xpath "//vm[name='Cloudforms']/status/state/text()" - || true
      changed_when: false
      register: vm_status
      until: vm_status.stdout == 'down'
      retries: 30
      delay: 10
      delegate_to: "{{ infrastructure_delegate_rhel7_host_used_to_perform_xpath_select_on_curl_results }}"
      when: cloudforms_vm_id.stdout != ""

    - name: remove Cloudforms VM
      ovirt:
        user: admin@internal
        url: "https://localhost"
        instance_name: Cloudforms
        password: "{{ root_password }}"
        state: absent
      delegate_to: rhevm
      when: cloudforms_vm_id.stdout != ""

  when: mode == 'destroy'
